{{- if .Values.cloudflared.enabled }}
{{- $secretName := .Values.cloudflared.existingSecretName | default (printf "%s-cloudflared-token" (include "cloudflare-tunnel-operator.fullname" .)) }}
{{- $secretNs := .Values.cloudflared.existingSecretNamespace | default .Release.Namespace }}

{{- if .Values.cloudflared.tunnelToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $secretNs }}
type: Opaque
stringData:
  token: {{ .Values.cloudflared.tunnelToken | quote }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflare-tunnel-operator.fullname" . }}-cloudflared
  labels:
    {{- include "cloudflare-tunnel-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ $secretName }}
              key: token
{{- end }}
